import xml.etree.ElementTree as ET

XML_VERSION = "12.1.0"

# Define namespaces
XML_NS_MAP = {
    None: "urn://www.factorytalk.net/schema/2003/FTLDDAlarms.xsd",
    "dt": "urn:schemas-microsoft-com:datatypes",
    "xsi": "http://www.w3.org/2001/XMLSchema-instance",
}

# Create the root element with the defined namespaces and attributes
XML_ROOT = ET.Element("FTAeAlarmStore", attrib={
    "xmlns:dt": XML_NS_MAP["dt"],
    "xmlns": XML_NS_MAP[None],
    "xmlns:xsi": XML_NS_MAP["xsi"]#,
    #"xsi:schemaLocation": "urn://www.factorytalk.net/schema/2003/FTLDDAlarms.xsd FTLDDAlarms.xsd"
})


POLL_GROUPS = ["0.10", "0.25", "0.50", "1","2","5","10","20","30","60","120"]

DEFAULT_POLL_INDEX = 4 # 2 seconds

SHELVE_MAX_VALUE = 480

DETECTOR_COMMAND = "FTAeDetectorCommand"

SIMULATED_SEVERITY  = 101
BYPASSED_SEVERITY   = 101
MODFAULT_SEVERITY   = 501
SAFETY_SEVERITY     = 901

# Alarms are repeated across many AOI's
ALARM_DEFINITIONS = {
    "ModuleFaulted": {
        "Name": "PLCNAME_TAGNAME_Alm_ModuleFaulted",
        "Type": "Tag",
        "Style": "DiscreteTrue",
        "Msg": "Module is in faulted state",
        "MsgID": 10001,
        "Params": {},
        "Severity": str(MODFAULT_SEVERITY),
        "DataItem": "TAGPATH.Sts_IOFault",
        "Enabled" : False, 
    },
    "P_Alarm":{
        "Name": "PLCNAME_TAGNAME_Alm",
        "Type": "P_Alarm",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/',
        "MsgID": 10002,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Cond"},
        "Severity": "TAGPATH.Cfg_Severity",
        "DataItem": "TAGPATH.Alm", 
        "Enabled" : True,  
    },
    "Bypassed":{
        "Name": "PLCNAME_TAGNAME_Alm_BypassEnabled",
        "Type": "Tag",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Permissive and interlock are being bypassed.',
        "MsgID": 10003,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": str(BYPASSED_SEVERITY),
        "DataItem": "TAGPATH.Sts_BypActive",
        "Enabled" : True,               
    },
    "Simulated":{
        "Name": "PLCNAME_TAGNAME_Alm_Simulated",
        "Type": "Tag",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Input is being simulated. This can defeat interlocks and safety systems.',
        "MsgID": 10004,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Cmd": "NavToFaceplate TAGPATH PROGPATH",
        "Severity": str(SIMULATED_SEVERITY),
        "DataItem": "TAGPATH.Sts_SubstPV",
        "Enabled" : True,                    
    },
    "Fail":{
        "Name": "PLCNAME_TAGNAME_Alm_Fail",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg":'/*S:0%Tag1*/ - /*S:0%Tag2*/ - Input bad or uncertain. Val=/*N:5 %Tag3 NOFILL DP:1*/;',
        "MsgID": 10005,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc","Tag3":".Val"},
        "Severity": "TAGPATH.Cfg_FailSeverity",
        "DataItem": "TAGPATH.Alm_Fail",
        "Enabled" : False, 
    },
    "HiHi":{
        "Name": "PLCNAME_TAGNAME_Alm_HiHi",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - High-High Alarm;  Val=/*N:5 %Tag3 NOFILL DP:1*/;',
        "MsgID": 10006,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc","Tag3":".Val"},
        "Severity": "TAGPATH.Cfg_HiHiSeverity",
        "DataItem": "TAGPATH.Alm_HiHi",
        "Enabled" : True, 
    },
    "Hi":{
        "Name": "PLCNAME_TAGNAME_Alm_Hi",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - High Alarm;  Val=/*N:5 %Tag3 NOFILL DP:1*/;',
        "MsgID": 10007,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc","Tag3":".Val"},
        "Severity": "TAGPATH.Cfg_HiSeverity",
        "DataItem": "TAGPATH.Alm_Hi",
        "Enabled" : True,           
    },
    "Lo":{
        "Name": "PLCNAME_TAGNAME_Alm_Lo",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Low Alarm;  Val=/*N:5 %Tag1 NOFILL DP:1*/;',
        "MsgID": 10008,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc","Tag3":".Val"},
        "Severity": "TAGPATH.Cfg_LoSeverity",
        "DataItem": "TAGPATH.Alm_Lo",
        "Enabled" : True,                
    },
    "LoLo":{
        "Name": "PLCNAME_TAGNAME_Alm_LoLo",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Low-Low Alarm;  Val=/*N:5 %Tag1 NOFILL DP:1*/;',
        "MsgID": 10009,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc","Tag3":".Val"},
        "Severity": "TAGPATH.Cfg_LoLoSeverity",
        "DataItem": "TAGPATH.Alm_LoLo",
        "Enabled" : True,                    
    },
    "HiRoC":{
        "Name": "PLCNAME_TAGNAME_Alm_HiRoC",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - High Rate of Change Alarm; Val=/*N:5 %Tag3 NOFILL DP:1*/;',
        "MsgID": 10010,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc","Tag3":".Val"},
        "Severity": "TAGPATH.Cfg_HiRoCSeverity",
        "DataItem": "TAGPATH.Alm_HiRoC",
        "Enabled" : True,                    
    },
    "HiDev":{
        "Name": "PLCNAME_TAGNAME_Alm_HiDev",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - High Deviation Alarm;  Val=/*N:5 %Tag1 NOFILL DP:1*/;',
        "MsgID": 10011,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc","Tag3":".Val"},
        "Severity": "TAGPATH.Cfg_HiDevSeverity",
        "DataItem": "TAGPATH.Alm_HiDev",
        "Enabled" : True,                    
    },
    "HiHiDev":{
        "Name": "PLCNAME_TAGNAME_Alm_HiHiDev",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - High-High Deviation Alarm',
        "MsgID": 10030,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": "TAGPATH.Cfg_HiHiDevSeverity",
        "DataItem": "TAGPATH.Alm_HiHiDev",
        "Enabled" : True,                    
    },
    "LoDev":{
        "Name": "PLCNAME_TAGNAME_Alm_LoDev",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Low Deviation Alarm;  Val=/*N:5 %Tag1 NOFILL DP:1*/;',
        "MsgID": 10012,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc","Tag3":".Val"},
        "Severity": "TAGPATH.Cfg_LoDevSeverity",
        "DataItem": "TAGPATH.Alm_LoDev",
        "Enabled" : True,                    
    },
    "LoLoDev":{
        "Name": "PLCNAME_TAGNAME_Alm_LoLoDev",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Low-Low Deviation Alarm',
        "MsgID": 10031,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": "TAGPATH.Cfg_LoLoDevSeverity",
        "DataItem": "TAGPATH.Alm_LoLoDev",
        "Enabled" : True,                    
    },
    "Diff":{
        "Name": "PLCNAME_TAGNAME_Alm_LoLo",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Differential Limit Exceeded; Val_Diff=/*N:5 %Tag3 NOFILL DP:0*/',
        "MsgID": 10013,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc","Tag3":".Val_Diff"},
        "Severity": "TAGPATH.Cfg_DiffSeverity",
        "DataItem": "TAGPATH.Alm_Diff",
        "Enabled" : True,                    
    },
    "NoneGood":{
        "Name": "PLCNAME_TAGNAME_Alm_NoneGood",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - PVA and PVB Both Bad Quality;  Val_PVA=/*N:5 %Tag3 NOFILL DP:1*/; Val_PVB=/*N:5 %Tag4 NOFILL DP:1*/;',
        "MsgID": 10014,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc","Tag3":".Val_PVA","Tag4":".Val_PVB"},
        "Severity": "TAGPATH.Cfg_NoneGoodSeverity",
        "DataItem": "TAGPATH.Alm_NoneGood",
        "Enabled" : True,                                
    },
    "OneGood":{
        "Name": "PLCNAME_TAGNAME_Alm_OneGood",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - PVA and PVB One Bad Quality;  Val_PVA=/*N:5 %Tag3 NOFILL DP:1*/; Val_PVB=/*N:5 %Tag4 NOFILL DP:1*/;',
        "MsgID": 10015,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc","Tag3":".Val_PVA","Tag4":".Val_PVB"},
        "Severity": "TAGPATH.Cfg_OneGoodSeverity",
        "DataItem": "TAGPATH.Alm_OneGood",
        "Enabled" : True,                   
    },
    "IOFault":{
        "Name": "PLCNAME_TAGNAME_Alm_IOFault",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - IO Fault',
        "MsgID": 10016,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": "TAGPATH.Cfg_IOFaultSeverity",
        "DataItem": "TAGPATH.Alm_IOFault",
        "Enabled" : False,                    
    },
    "IntlkTrip":{
        "Name": "PLCNAME_TAGNAME_Alm_IntlkTrip",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Interlock Trip - /*S:20%Tag3*/',
        "MsgID": 10017,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc","Tag3":"_Intlk.Val_FirstOutTxt"},
        "Severity": "TAGPATH.Cfg_IntlkTripSeverity",
        "DataItem": "TAGPATH.Alm_IntlkTrip",
        "Enabled" : True,                  
    },
    "ActuatorFault":{
        "Name": "PLCNAME_TAGNAME_Alm_ActuatorFault",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Actuator fault.  Val_Fault=/*S:0%Tag1*/;',
        "MsgID": 10018,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc","Tag3":".Val_Fault"},
        "Severity": "TAGPATH.Cfg_ActuatorFaultSeverity",
        "DataItem": "TAGPATH.Alm_ActuatorFault",
        "Enabled" : True,              
    },
    "FullStall":{
        "Name": "PLCNAME_TAGNAME_Alm_FullStall",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Full Stall - Valve did not move',
        "MsgID": 10019,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": "TAGPATH.Cfg_FullStallSeverity",
        "DataItem": "TAGPATH.Alm_FullStall",
        "Enabled" : True, 
    },
    "TransitStall":{
        "Name": "PLCNAME_TAGNAME_Alm_TransitStall",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Transit Stall - Valve did not move to target position',
        "MsgID": 10020,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": "TAGPATH.Cfg_TransitStallSeverity",
        "DataItem": "TAGPATH.Alm_TransitStall",
        "Enabled" : True, 
    },
    "TgtDisagree":{
        "Name": "PLCNAME_TAGNAME_Alm_TgtDisagree",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Target Disagree - PV Does Not Match Target',
        "MsgID": 10021,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": "TAGPATH.Cfg_TgtDisagreeSeverity",
        "DataItem": "TAGPATH.Alm_TgtDisagree",
        "Enabled" : True,                  
    },
    "OffFail":{
        "Name": "PLCNAME_TAGNAME_Alm_OffFail",        
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Off Failure - Device feedback does not confirm the device is OFF within the configured time',
        "MsgID": 10022,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": "TAGPATH.Cfg_OffFailSeverity",
        "DataItem": "TAGPATH.Alm_OffFail",
        "Enabled" : True,               
    },
    "OnFail":{
        "Name": "PLCNAME_TAGNAME_Alm_OnFail",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - On Failure - Device feedback does not confirm the device is ON within the configured time',
        "MsgID": 10023,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": "TAGPATH.Cfg_OnFailSeverity",
        "DataItem": "TAGPATH.Alm_OnFail",
        "Enabled" : True,                 
    },
    "FailToStart":{
        "Name": "PLCNAME_TAGNAME_Alm_FailToStart",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Fail to start',
        "MsgID": 10024,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": "TAGPATH.Cfg_FailToStartSeverity",
        "DataItem": "TAGPATH.Alm_FailToStart",
        "Enabled" : True,                 
    },
    "FailToStop":{
        "Name": "PLCNAME_TAGNAME_Alm_FailToStop",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Fail to stop',
        "MsgID": 10025,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": "TAGPATH.Cfg_FailToStopSeverity",
        "DataItem": "TAGPATH.Alm_FailToStop",
        "Enabled" : True,                 
    },
    "DriveFault":{
        "Name": "PLCNAME_TAGNAME_Alm_DriveFault",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Drive Fault',
        "MsgID": 10026,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": "TAGPATH.Cfg_DriveFaultSeverity",
        "DataItem": "TAGPATH.Alm_DriveFault",
        "Enabled" : False,   
    },
    "CantStart":{
        "Name": "PLCNAME_TAGNAME_Alm_CantStart",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Cannot start. No motors available to start',
        "MsgID": 10027,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": "TAGPATH.Cfg_CantStartSeverity",
        "DataItem": "TAGPATH.Alm_CantStart",
        "Enabled" : True,                  
    },
    "CantStop":{
        "Name": "PLCNAME_TAGNAME_Alm_CantStop",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Cannot stop. No motors available to stop',
        "MsgID": 10028,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": "TAGPATH.Cfg_CantStopSeverity",
        "DataItem": "TAGPATH.Alm_CantStop",
        "Enabled" : True,               
    },
    "Trip":{
        "Name": "PLCNAME_TAGNAME_Alm_Trip",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Device has tripped',
        "MsgID": 10032,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": "TAGPATH.Cfg_TripSeverity",
        "DataItem": "TAGPATH.Alm_Trip", 
        "Enabled" : True,              
    },  
    "Warn":{
        "Name": "PLCNAME_TAGNAME_Alm_Warn",
        "Type": "Embedded",
        "Style": "DiscreteTrue",
        "Msg": '/*S:0%Tag1*/ - /*S:0%Tag2*/ - Device has warning',
        "MsgID": 10033,
        "Params":{"Tag1":".Cfg_Tag","Tag2":".Cfg_Desc"},
        "Severity": "TAGPATH.Cfg_WarnSeverity",
        "DataItem": "TAGPATH.Alm_Warn",
        "Enabled" : True,               
    },
    "SafetyFaultPresent":{
        "Name": "PLCNAME_TAGNAME_Alm_SafetyInstructionFault",
        "Type": "Tag",
        "Style": "DiscreteTrue",
        "Msg": 'Safety Instruction Faulted - Fault Code /*S:0%Tag1*/ Diagnostic Code /*S:0%Tag2*/',
        "MsgID": 10040,
        "Params":{"Tag1":".FaultCode","Tag2":".DiagnosticCode"},
        "Cmd": "",
        "Severity": str(SAFETY_SEVERITY),
        "DataItem": "TAGPATH.FP",
        "Enabled" : True,   
    },
    "SIF_InputDiagnosticFault":{
        "Name": "PLCNAME_TAGNAME_SIF_InputDiagnosticFault",
        "Type": "Tag",
        "Style": "DiscreteFalse",
        "Msg": 'SIF Input Diagnostic Not OK',
        "MsgID": 10041,
        "Params":{},
        "Cmd": "",
        "Severity": str(SAFETY_SEVERITY),
        "DataItem": "TAGPATH.Sts_Diag_OK",
        "Enabled" : True,   
    },
    "SIF_InputHighLimitFault":{
        "Name": "PLCNAME_TAGNAME_SIF_InputHighLimitFault",
        "Type": "Tag",
        "Style": "DiscreteFalse",
        "Msg": 'SIF Input High Limit Exceeded',
        "MsgID": 10042,
        "Params":{},
        "Cmd": "",
        "Severity": str(SAFETY_SEVERITY),
        "DataItem": "TAGPATH.Sts_High_OK",
        "Enabled" : True,   
    },
    "SIF_InputLowLimitFault":{
        "Name": "PLCNAME_TAGNAME_SIF_InputLowLimitFault",
        "Type": "Tag",
        "Style": "DiscreteFalse",
        "Msg": 'SIF Input Low Limit Exceeded',
        "MsgID": 10043,
        "Params":{},
        "Cmd": "",
        "Severity": str(SAFETY_SEVERITY),
        "DataItem": "TAGPATH.Sts_Low_OK",
        "Enabled" : True,   
    },
    "SIF_InputPVStatusFault":{
        "Name": "PLCNAME_TAGNAME_SIF_InputPVStatusFault",
        "Type": "Tag",
        "Style": "DiscreteFalse",
        "Msg": 'SIF Input PV Status NOK',
        "MsgID": 10044,
        "Params":{},
        "Cmd": "",
        "Severity": str(SAFETY_SEVERITY),
        "DataItem": "TAGPATH.Sts_PV",
        "Enabled" : True,   
    },
    "SIF_Bypassed":{
        "Name": "PLCNAME_TAGNAME_SIF_Bypassed",
        "Type": "Tag",
        "Style": "DiscreteTrue",
        "Msg": 'SIF is currently being bypassed',
        "MsgID": 10045,
        "Params":{},
        "Cmd": "",
        "Severity": str(SAFETY_SEVERITY),
        "DataItem": "TAGPATH.Sts_Bypassed",
        "Enabled" : True,   
    },
    "SIF_Active":{
        "Name": "PLCNAME_TAGNAME_SIF_Active",
        "Type": "Tag",
        "Style": "DiscreteFalse",
        "Msg": 'SIF has been activated',
        "MsgID": 10046,
        "Params":{},
        "Cmd": "",
        "Severity": str(SAFETY_SEVERITY),
        "DataItem": "TAGPATH.Sts_OK",
        "Enabled" : True,   
    },
    "SIF_OutputDiagnosticFault":{
        "Name": "PLCNAME_TAGNAME_SIF_OutputDiagnosticFault",
        "Type": "Tag",
        "Style": "DiscreteFalse",
        "Msg": 'SIF Output Diagnostic Not OK',
        "MsgID": 10047,
        "Params":{},
        "Cmd": "",
        "Severity": str(SAFETY_SEVERITY),
        "DataItem": "TAGPATH.Sts_Diag_OK",
        "Enabled" : True,   
    },
    "SIF_FinalElementActive":{
        "Name": "PLCNAME_TAGNAME_SIF_FinalElementActive",
        "Type": "Tag",
        "Style": "DiscreteFalse",
        "Msg": 'SIF Output Final Element Activated',
        "MsgID": 10048,
        "Params":{},
        "Cmd": "",
        "Severity": str(SAFETY_SEVERITY),
        "DataItem": "TAGPATH.Sts_Safety_OK",
        "Enabled" : True,   
    },
}





# Define AOI configuration and messages

AOI_CONFIG = {
    "SIF_Input":{
        "SIF_InputDiagnosticFault": {},
        "SIF_InputHighLimitFault": {},
        "SIF_InputLowLimitFault": {},
    },
    "SIF_Logic":{
        "SIF_Bypassed": {},
        "SIF_Active": {},
    },
    "SIF_Output":{
        "SIF_OutputDiagnosticFault": {},
        "SIF_FinalElementActive": {},
    },
    "DCI_STOP":{
        "SafetyFaultPresent": {}
    },
    "CONFIGURABLE_ROUT":{
        "SafetyFaultPresent": {}
    },
    "L_ModuleSts":{
        "ModuleFaulted": {}
    },
    "P_AIChan": {
        "Fail":{}
    },
    "P_AIn": 
    {
        "Fail":{},
        "HiHi":{},
        "Hi":{},
        "Lo":{},
        "LoLo":{},
        "Simulated":{}    
    },
    "P_AInAdv": 
    {
        "Fail":{},
        "HiHi":{},
        "Hi":{},
        "Lo":{},
        "LoLo":{},
        "HiRoC":{},
        "HiDev":{},
        "LoDev":{},
        "Simulated":{}    
    },
    "P_AInDual": {
        "Fail":{},
        "HiHi":{},
        "Hi":{},
        "Lo":{},
        "LoLo":{},
        "Simulated":{},
        "Diff":{},
        "NoneGood":{},
        "OneGood":{},
        "Simulated":{},
    },
    "P_AOut": {
        "IOFault":{},
        "IntlkTrip":{},
        "Bypassed":{},
    },
    'P_ValveMO': {
        "ActuatorFault":{},
        "FullStall":{},
        "IOFault":{},
        "IntlkTrip":{},              
        "TransitStall":{},
        "Bypassed":{},
    },
    'P_ValveC': {
        "ActuatorFault":{},
        "IOFault":{},
        "IntlkTrip":{}, 
        "Bypassed":{},
    },
    'P_ValveSO': {
        "FullStall":{},
        "IOFault":{},
        "IntlkTrip":{},
        "TransitStall":{},
        "Bypassed":{},
    },
    'P_DIn': {
        "IOFault":{},
        "TgtDisagree":{},
        "Simulated":{},
    },
    'P_DOut': {
        "IOFault":{},
        "IntlkTrip":{},
        "OffFail":{},
        "OnFail":{},
        "Bypassed":{},
    },
    'P_E300Ovld':{
        "IOFault":{},
        "Trip":{},
        "Warn":{},
    },
    'P_PIDE': {
        "Fail":{},
        "HiHiDev":{},
        "HiDev":{},
        "LoDev":{},
        "LoLoDev":{},
        "IntlkTrip":{},
        "Bypassed":{},
    },
    'P_Motor': {
        "FailToStart":{},
        "FailToStop":{},
        "IOFault":{},
        "IntlkTrip":{},
        "Bypassed":{},
    },
    'P_PF755': {
        "DriveFault":{},
        "FailToStart":{},
        "FailToStop":{},
        "IOFault":{},
        "IntlkTrip":{},
        "Bypassed":{},
    },
    'P_VSD': {
        "DriveFault":{},
        "FailToStart":{},
        "FailToStop":{},
        "IOFault":{},
        "IntlkTrip":{},
        "Bypassed":{},
    },
    'P_LLS': {
        "CantStart":{},
        "CantStop":{},
        "IntlkTrip":{},
        "Bypassed":{},
    },
    "P_Alarm": {
        "P_Alarm":{},
    },
}


# These tags are always in a P_Alarm AOI
P_ALARM_TAGS = ['.Com_AE.1','.Com_AE.4','.Com_AE.5','.Com_AE.7','.Com_AE.8','.Com_AE.10','.Com_AE.11','.Cfg_MaxShelfT']

ALARM_TYPE_CONFIG = {
    'Embedded': {
        "Name": "PLCNAME_TAGNAME_Alm_ALMNAME",
        "Cmd": "NavToFaceplate TAGPATH PROGPATH",
        "DisabledDataItem": "TAGPATH.ALMTAG.Com_AE.9",
        "AckedDataItem": "TAGPATH.ALMTAG.Com_AE.1",
        "SuppressedDataItem": "TAGPATH.ALMTAG.Com_AE.6",
        "ShelvedDataItem": "TAGPATH.ALMTAG.Com_AE.3",
        "RemoteAckAllDataItem": "TAGPATH.ALMTAG.Com_AE.1",
        "RemoteDisableDataItem": "TAGPATH.ALMTAG.Com_AE.10",
        "RemoteEnableDataItem": "TAGPATH.ALMTAG.Com_AE.11",
        "RemoteSuppressDataItem": "TAGPATH.ALMTAG.Com_AE.7",
        "RemoteUnSuppressDataItem": "TAGPATH.ALMTAG.Com_AE.8",
        "RemoteShelveAllDataItem": "TAGPATH.ALMTAG.Com_AE.4",
        "RemoteUnShelveDataItem": "TAGPATH.ALMTAG.Com_AE.5",
        "RemoteShelveDuration": "TAGPATH.ALMTAG.Cfg_MaxShelfT",
    },
    'P_Alarm': {
        "Name": "PLCNAME_TAGNAME_Alm",
        "Cmd": "AE_DisplayP_AlarmFaceplate TAGPATH PROGPATH TAGPATH.Cfg_Cond",
        "DisabledDataItem": "TAGPATH.Com_AE.9",
        "AckedDataItem": "TAGPATH.Com_AE.1",
        "SuppressedDataItem": "TAGPATH.Com_AE.6",
        "ShelvedDataItem": "TAGPATH.Com_AE.3",
        "RemoteAckAllDataItem": "TAGPATH.Com_AE.1",
        "RemoteDisableDataItem": "TAGPATH.Com_AE.10",
        "RemoteEnableDataItem": "TAGPATH.Com_AE.11",
        "RemoteSuppressDataItem": "TAGPATH.Com_AE.7",
        "RemoteUnSuppressDataItem": "TAGPATH.Com_AE.8",
        "RemoteShelveAllDataItem": "TAGPATH.Com_AE.4",
        "RemoteUnShelveDataItem": "TAGPATH.Com_AE.5",
        "RemoteShelveDuration": "TAGPATH.Cfg_MaxShelfT",
    },
    "Tag": {
        "Name": "PLCNAME_TAGNAME_Alm_ALMNAME",
        "Cmd": "NavToFaceplate TAGPATH PROGPATH",
        "DisabledDataItem": "",
        "AckedDataItem": "",
        "SuppressedDataItem": "",
        "ShelvedDataItem": "",
        "RemoteAckAllDataItem": "",
        "RemoteDisableDataItem": "",
        "RemoteEnableDataItem": "",
        "RemoteSuppressDataItem": "",
        "RemoteUnSuppressDataItem": "",
        "RemoteShelveAllDataItem": "",
        "RemoteUnShelveDataItem": "",
        "RemoteShelveDuration": "",
    }  
}


